config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
  }
  root 'messages#about'
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :messages do
    collection do
      get 'search' 
    end
    resources :helpful_messages, only: [:create, :destroy]
    resources :comments, only: [:index, :create, :edit, :update, :destroy]
  end
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :helpful_messages, dependent: :destroy
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :generation
  belongs_to_active_hash :genre
  belongs_to_active_hash :body_parts
  belongs_to_active_hash :category

  with_options presence: true do
    validates :content
    validates :generation_id, numericality: { other_than: 1 }
    validates :genre_id, numericality: { other_than: 1 }
    validates :body_parts_id, numericality: { other_than: 1 }
    validates :category_id, numericality: { other_than: 1 }
  end

  def self.search(search)
    if search != ""
      Message.where('content LIKE(?)', "%#{search}%")
    else
      Message.all
    end 
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def about
    
  end

  def index
    @messages = Message.all.order('created_at DESC')
  end

  def new
    @message = Message.new
  end
  
  def create
    @message = Message.create(message_params)
    if @message.save
      flash[:notice] = "メッセージを作成しました"
      redirect_to user_path(current_user.id)
    else
      render :new
    end
  end

  def edit
    @message = Message.find(params[:id])
    redirect_to root_path if current_user.id != @message.user_id
  end
  
  def update
    @message = Message.find(params[:id])
    redirect_to root_path if current_user.id != @message.user_id
    if @message.update(message_params)
      flash[:notice] = "メッセージを更新しました"
      redirect_to message_comments_path(@message.id)
    else
      render :edit
    end
  end

  def destroy
    @message = Message.find(params[:id])
    redirect_to root_path if current_user.id != @message.user_id
    if @message.destroy
      flash[:notice] = "メッセージを削除しました"
      redirect_to user_path(current_user.id) 
    end
  end

  def search
    @messages = Message.search(params[:keyword]) 
  end

  private

  def message_params
    params.require(:message).permit(
      :content,
      :generation_id,
      :genre_id,
      :body_parts_id,
      :category_id,
      :user_id
    ).merge(user_id: current_user.id)
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/about.html.erb
<div class="about">
  <div class="box1">
    <h1 class="box-title">baseball-infoとは</h1><br>
    <p class="box-content">baseball-infoは、野球についてもっと知りたい、語りたいという思いを実現するために作られたサービスです。</p><br>
  </div>
  <div class="box2">
    <h1 class="box-title">野球について見識を深める</h1><br>
    <p class="box-content">baseball-infoは、野球についての様様な意見、主張、質問などのメッセージが投稿されています。それらを知ることで野球についてより一層見識を深めることができます。あなたも早速いろんなメッセージを見てみましょう！</p><br><br>
    <div class="box-btn">
      <%= link_to 'メッセージを見てみる！', messages_path, class: "btn-about" %>
    </div><br>
  </div>
  <div class="box3">
    <h1 class="box-title">メッセージを投稿してみよう</h1><br>
    <p class="box-content">baseball-infoでは、会員登録することで、野球についてのことを、メッセージとして投稿することができます。普段考えていることや主張したいこと、困っていてアドバイスが欲しいことなど、様々なことを投稿することができます。投稿されたメッセージに対してコメントをもらうことで、悩みが解決したり、野球についての見識を深めることができます。また、自身が行った今日の練習内容をアウトプットするために投稿することもできます。そのメッセージが他の誰かにとって有益な情報になるかもしれないからです。さあ、まずは会員登録してみよう！</p><br><br>
    <div class="box-btn">
      <%= link_to '会員登録してみよう！', new_user_registration_path, class: "btn-about" %><br>
    </div><br>
  </div>
</div>

app/views/messages/edit.html.erb
<div class="message-title">メッセージの編集</div>

<div class="message-contents">

  <%= form_with model: @message, local: true do |f| %>
  
  <div class="message-box">

    <%= render "shared/error_messages", model: f.object %>

    <div class="message-info">
      <%= f.label "メッセージ" %><br />
      <%= f.text_area :content, class:"content", placeholder:"野球に関しての自身の意見、主張などを自由に記入してください。また、アドバイスが欲しいこと、他の人の意見をもらいたいことなどの質問を記入してもらって構いません。最近自分が取り組んでいることを記入してアウトプットの場として使っていただいて構いません。自由に記述してください。" %>
    </div>

    <div class="message-info">
      <%= f.label "世代" %><br />
      <%= f.collection_select(:generation_id, Generation.all, :id, :name, {}, {class:"tag"}) %>
    </div>

    <div class="message-info">
      <%= f.label "ジャンル" %><br />
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"tag"}) %>
    </div>

    <div class="message-info">
      <%= f.label "体の部位" %><br />
      <%= f.collection_select(:body_parts_id, BodyParts.all, :id, :name, {}, {class:"tag"}) %>
    </div>

    <div class="message-info">
      <%= f.label "メッセージカテゴリー" %><br />
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"tag"}) %>
    </div>

  </div>

    <%= f.submit "上記の内容でメッセージを更新する" ,class:"message-btn" %>

  <% end %>

</div>

app/views/messages/index.html.erb
<div class="search-contents">
  <%= form_with(url: search_messages_path, local: true, method: :get) do |form| %>
  <div class="search-box"><br>
    <%= form.text_field :keyword, placeholder: "メッセージを検索する", class: "search-form" %>
    <%= form.submit "検索", class: "search-btn" %>
  </div>
  <% end %>
</div>

<div class="message-title">メッセージ一覧</div>

<div class="message-contents">
  <% @messages.each do |message| %>
  <div class="message-box">
    <div class="message-top">
      <%= link_to message_comments_path(message.id), class: "message-show" do %>
        <%= message.content %>
      <% end %>
    </div>
    <div class="message-middle">
      <div>
        ユーザー名：
        <%= link_to user_path(message.user.id) do %>
          <%= message.user.nickname %>
        <% end %>
      </div>
      <div>日時：<%= l message.created_at %></div>
    </div>
    <div class="message-buttom">

      <%# いいねボタンのコード %>
      <div class="good">
        <% if user_signed_in? %>
          <% if helpful_message = HelpfulMessage.find_by(user_id: current_user.id, message_id: message.id) %>
            <%= link_to message_helpful_message_path(message.id, helpful_message.id), method: :delete do %>
              <span class="fa far fa-thumbs-up ungood-btn"></span>
            <% end %>
          <% else %>
            <%= link_to message_helpful_messages_path(message.id), method: :post do %>
              <span class="fa far fa-thumbs-up good-btn"></span>
            <% end %>
          <% end %>
        <% else %>
          <div class="fa far fa-thumbs-up ungood-btn"></div>
        <% end %>
        <div><%= HelpfulMessage.where(message_id: message.id).count %></div>
      </div>

      <div>世代：<%= message.generation.name %></div>        
      <div>ジャンル：<%= message.genre.name %></div>
      <div>体の部位：<%= message.body_parts.name %></div>
      <div>メッセージカテゴリー：<%= message.category.name %></div>
    </div>
  </div>
  <% end %>
</div>

app/views/messages/new.html.erb
<div class="message-title">新規メッセージ作成</div>

<div class="message-contents">

  <%= form_with model: @message, local: true do |f| %>
  
  <div class="message-box">

    <%= render "shared/error_messages", model: f.object %>

    <div class="message-info">
      <%= f.label "メッセージ" %><br />
      <%= f.text_area :content, class:"content", placeholder:"野球に関しての自身の意見、主張などを自由に記入してください。また、アドバイスが欲しいこと、他の人の意見をもらいたいことなどの質問を記入してもらって構いません。最近自分が取り組んでいることを記入してアウトプットの場として使っていただいて構いません。自由に記述してください。" %>
    </div>

    <div class="message-info">
      <%= f.label "世代" %><br />
      <%= f.collection_select(:generation_id, Generation.all, :id, :name, {}, {class:"tag"}) %>
    </div>

    <div class="message-info">
      <%= f.label "ジャンル" %><br />
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"tag"}) %>
    </div>

    <div class="message-info">
      <%= f.label "体の部位" %><br />
      <%= f.collection_select(:body_parts_id, BodyParts.all, :id, :name, {}, {class:"tag"}) %>
    </div>

    <div class="message-info">
      <%= f.label "メッセージカテゴリー" %><br />
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"tag"}) %>
    </div>

  </div>

    <%= f.submit "上記の内容でメッセージを作成する" ,class:"message-btn" %>

  <% end %>

</div>

app/views/messages/search.html.erb
<div class="search-contents">
  <%= form_with(url: search_messages_path, local: true, method: :get) do |form| %>
  <div class="search-box"><br>
    <%= form.text_field :keyword, placeholder: "メッセージを検索する", class: "search-form" %>
    <%= form.submit "検索", class: "search-btn" %>
  </div>
  <% end %>
</div>

<div class="message-title">該当するメッセージ一覧</div>

<div class="message-contents">
  <% @messages.each do |message| %>
  <div class="message-box">
    <div class="message-top">
      <%= link_to message_comments_path(message.id), class: "message-show" do %>
        <%= message.content %>
      <% end %>
    </div>
    <div class="message-middle">
      <div>
        ユーザー名：
        <%= link_to user_path(message.user.id) do %>
          <%= message.user.nickname %>
        <% end %>
      </div>
      <div>日時：<%= l message.created_at %></div>
    </div>
    <div class="message-buttom">

      <%# いいねボタンのコード %>
      <div class="good">
        <% if user_signed_in? %>
          <% if helpful_message = HelpfulMessage.find_by(user_id: current_user.id, message_id: message.id) %>
            <%= link_to message_helpful_message_path(message.id, helpful_message.id), method: :delete do %>
              <span class="fa far fa-thumbs-up ungood-btn"></span>
            <% end %>
          <% else %>
            <%= link_to message_helpful_messages_path(message.id), method: :post do %>
              <span class="fa far fa-thumbs-up good-btn"></span>
            <% end %>
          <% end %>
        <% else %>
          <div class="fa far fa-thumbs-up ungood-btn"></div>
        <% end %>
        <div><%= HelpfulMessage.where(message_id: message.id).count %></div>
      </div>

      <div>世代：<%= message.generation.name %></div>        
      <div>ジャンル：<%= message.genre.name %></div>
      <div>体の部位：<%= message.body_parts.name %></div>
      <div>メッセージカテゴリー：<%= message.category.name %></div>
    </div>
  </div>
  <% end %>
  <% if @messages.length == 0 %>
    <%= "該当するメッセージはありません" %>
  <% end %>
</div>