config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
  }
  root 'messages#about'
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :messages do
    collection do
      get 'search' 
    end
    resources :helpful_messages, only: [:create, :destroy]
    resources :comments, only: [:index, :create, :edit, :update, :destroy]
  end
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :message

  validates :comment, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]

  def index
    @comment = Comment.new
    @message = Message.find(params[:message_id])
    @comments = @message.comments.includes(:user)
  end
  def create
    @message = Message.find(params[:message_id])
    @comment = @message.comments.new(comment_params)
    if @comment.save
      flash[:notice] = "コメントを作成しました"
      redirect_to message_comments_path(@message.id)
    else
      @comments = @message.comments.includes(:user)
      render :index
    end
  end

  def edit
    @message = Message.find(params[:message_id])
    @comment = Comment.find(params[:id])
    redirect_to root_path if current_user.id != @comment.user_id
  end

  def update
    @message = Message.find(params[:message_id])
    @comment = Comment.find(params[:id])
    redirect_to root_path if current_user.id != @comment.user_id
    if @comment.update(comment_params)
      flash[:notice] = "コメントを更新しました"
      redirect_to message_comments_path(@comment.message_id)
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    redirect_to root_path if current_user.id != @comment.user_id
    if @comment.destroy
      flash[:notice] = "コメントを削除しました"
      redirect_to message_comments_path(@comment.message_id) 
    end
  end

  private

  def comment_params
    params.require(:comment).permit(
      :comment,
      :user_id,
      :message_id
    ).merge(user_id: current_user.id)
  end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<div class="message-title">メッセージ詳細</div>

<div class="message-contents">
  <div class="message-box">
    <div class="message-top">
      <%= link_to message_comments_path(@message.id), class: "message-show" do %>
        <%= @message.content %>
      <% end %>
    </div>
    <div class="message-middle">
      <div>
        ユーザー名：
        <%= link_to user_path(@message.user.id) do %>
          <%= @message.user.nickname %>
        <% end %>
      </div>
      <div>日時：<%= l @message.created_at %></div>
    </div>
    <div class="message-buttom">
      <div>世代：<%= @message.generation.name %></div>        
      <div>ジャンル：<%= @message.genre.name %></div>
      <div>体の部位：<%= @message.body_parts.name %></div>
      <div>メッセージカテゴリー：<%= @message.category.name %></div>
    </div>
  </div>
</div>

<div class="comment-form">
    <div class="comment-form-title">このメッセージに対するコメントを編集する</div>
    <%= form_with model: [@message, @comment], local: true do |f| %>
      <%= render "shared/error_messages", model: f.object %>
      <div class="comment-form-comment">
        <%= f.text_area :comment, class:"comment-form-input", placeholder:"メッセージに対するコメントを記入してください" %>
      </div><br>
      <div>
        <%= f.submit "上記の内容でコメントを更新する" ,class:"comment-btn" %>
      </div><br>
    <% end %>
  </div>

app/views/comments/index.html.erb
<div class="message-title">メッセージ詳細</div>

<div class="message-contents">
  <div class="message-box">
    <div class="message-top">
      <%= link_to message_comments_path(@message.id), class: "message-show" do %>
        <%= @message.content %>
      <% end %>
    </div>
    <div class="message-middle">
      <div>
        ユーザー名：
        <%= link_to user_path(@message.user.id) do %>
          <%= @message.user.nickname %>
        <% end %>
      </div>
      <div>日時：<%= l @message.created_at %></div>
    </div>
    <div class="message-buttom">

    <%# いいねボタンのコード %>
      <div class="good">
        <% if user_signed_in? %>
          <% if helpful_message = HelpfulMessage.find_by(user_id: current_user.id, message_id: @message.id) %>
            <%= link_to message_helpful_message_path(@message.id, helpful_message.id), method: :delete do %>
              <span class="fa far fa-thumbs-up ungood-btn"></span>
            <% end %>
          <% else %>
            <%= link_to message_helpful_messages_path(@message.id), method: :post do %>
              <span class="fa far fa-thumbs-up good-btn"></span>
            <% end %>
          <% end %>
        <% else %>
          <div class="fa far fa-thumbs-up ungood-btn"></div>
        <% end %>
        <div><%= HelpfulMessage.where(message_id: @message.id).count %></div>
      </div>

      <div>世代：<%= @message.generation.name %></div>        
      <div>ジャンル：<%= @message.genre.name %></div>
      <div>体の部位：<%= @message.body_parts.name %></div>
      <div>メッセージカテゴリー：<%= @message.category.name %></div>
    </div>
  </div>
</div>

<div class="message-edit-destroy">
  <% if user_signed_in? && @message.user_id == current_user.id %>
    <%= link_to 'このメッセージを編集', edit_message_path(@message.id), class: "message-btn" %>
    <%= link_to 'このメッセージを削除する', message_path(@message.id), method: :delete, class: "message-btn" %>
  <% end %>
</div>


<div class="comment-title">このメッセージに対するコメント一覧</div>

<div class="comment-contents">
  <% @comments.each do |comment| %>
  <div class="comment-box">
    <div class="comment-top">
      <%= comment.comment %>
    </div>
    <div class="comment-bottom">
      <div class="comment-user">
        ユーザー名：
        <%= link_to user_path(comment.user.id) do %>
          <%= comment.user.nickname %>
        <% end %>
      </div>
      <div class="comment-date">日時：<%= l comment.created_at %></div>
    </div>

    <% if user_signed_in? && comment.user_id == current_user.id %>
      <div class="comment-edit-destroy">
        <%= link_to 'このコメントを編集', edit_message_comment_path(@message.id, comment.id), class: "comment-edit-btn" %>
        <%= link_to 'このコメントを削除する', message_comment_path(@message.id, comment.id), method: :delete, class: "comment-edit-btn" %>
      </div>
    <% end %>

  </div>
  <% end %>
</div>


<% if user_signed_in? %>
  <div class="comment-form">
    <div class="comment-form-title">このメッセージに対するコメントを作成する</div>
    <%= form_with model: [@message, @comment], local: true do |f| %>
      <%= render "shared/error_messages", model: f.object %>
      <div class="comment-form-comment">
        <%= f.text_area :comment, class:"comment-form-input", placeholder:"メッセージに対するコメントを記入してください" %>
      </div><br>
      <div>
        <%= f.submit "上記の内容でコメントを作成する" ,class:"comment-btn" %>
      </div><br>
    <% end %>
  </div>
<% end %>