config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
  }
  root 'messages#about'
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :messages do
    collection do
      get 'search' 
    end
    resources :helpful_messages, only: [:create, :destroy]
    resources :comments, only: [:index, :create, :edit, :update, :destroy]
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :messages, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :helpful_messages, dependent: :destroy

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/.freeze

  validates :email, uniqueness: { case_sensitive: true }, format: { with: EMAIL_REGEX }
  validates :password, format: { with: PASSWORD_REGEX }
  validates :nickname, presence: true, uniqueness: { case_sensitive: true }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @messages = Message.where(user_id: @user.id).order('created_at DESC')
    @helpful_message_count = 0
    @messages.each do |message|
      count = HelpfulMessage.where(message_id: message.id).count
      @helpful_message_count += count
    end
  end

  # 編集画面作成に断念のため
  # def edit
  #   redirect_to root_path if current_user.id != @user.id
  # end
  
  # def update
  #   if current_user.update(user_params)
  #     redirect_to user_path(current_user.id)
  #   else
  #     render :edit
  #   end
  # end

  def destroy
    @user = User.find(params[:id])
    redirect_to root_path if current_user.id != @user.id
    if @user.destroy
      flash[:notice] = "退会しました"
      redirect_to root_path 
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :password)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="registration-main">

  <h1><%= current_user.nickname %>のユーザー情報の編集</h1>

  <%= form_with model: current_user, class: 'form-content', local: true do |f| %>
  <%# エラー文を表示できないため断念 %>
    <%# <%= render "devise/shared/error_messages", model: f.object %> 

    <div class="field">
      <%= f.label "ニックネーム" %><br />
      <%= f.text_area :nickname, placeholder:"例) 太郎", maxlength:"40" %>
    </div>

    <div class="field">
      <%= f.label "メールアドレス" %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>

    <div class="field">
      <%= f.label "パスワード" %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "new-password" %>
    </div>

    <div class="actions">
      <%= f.submit "編集内容を更新する", class: "btn" %>
    </div>

  <% end %>

</div>

app/views/users/index.html.erb
<div class="user-title">ユーザー一覧</div>

<div class="user-contents">
  <% @users.each do |user| %>
    <div class="user-box">
      <%= link_to "#{user.nickname}", user_path(user.id), class: "user-name" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user-title">
  <%= @user.nickname %>のユーザーページ
</div>

<div class="user-count">
  <%= @user.nickname %>の獲得<span class="fa far fa-thumbs-up ungood-btn"></span>メッセージ数   <%= @helpful_message_count %>
</div>


<% if user_signed_in? && @user.id == current_user.id %>

<div class="user-contents">
  <div class="user-box">
      <div class="user-info">
        <p>ニックネーム</p><br/>
        <%= @user.nickname %>
      </div>
      <div class="user-info">
        <p>メールアドレス</p><br/>
        <%= @user.email %>
      </div>
  </div>
  <div class="user-edit-destroy">
    <%= link_to '編集する', edit_user_registration_path, class: "user-btn" %>
    <%= link_to '退会する', user_path(@user.id), method: :delete, class: "user-btn" %>
  </div>
</div>

<% end %>

<div class="message-title"><%= @user.nickname %>のメッセージ一覧</div>

<div class="message-contents">
  <% @messages.each do |message| %>
  <div class="message-box">
    <div class="message-top">
      <%= link_to message_comments_path(message.id), class: "message-show" do %>
        <%= message.content %>
      <% end %>
    </div>
    <div class="message-middle">
      <div>
        ユーザー名：
        <%= link_to user_path(message.user.id) do %>
          <%= message.user.nickname %>
        <% end %>
      </div>
      <div>日時：<%= l message.created_at %></div>
    </div>
    <div class="message-buttom">

      <%# いいねボタンのコード %>
      <div class="good">
        <% if user_signed_in? %>
          <% if helpful_message = HelpfulMessage.find_by(user_id: current_user.id, message_id: message.id) %>
            <%= link_to message_helpful_message_path(message.id, helpful_message.id), method: :delete do %>
              <span class="fa far fa-thumbs-up ungood-btn"></span>
            <% end %>
          <% else %>
            <%= link_to message_helpful_messages_path(message.id), method: :post do %>
              <span class="fa far fa-thumbs-up good-btn"></span>
            <% end %>
          <% end %>
        <% else %>
          <div class="fa far fa-thumbs-up ungood-btn"></div>
        <% end %>
        <div><%= HelpfulMessage.where(message_id: message.id).count %></div>
      </div>

      <div>世代：<%= message.generation.name %></div>        
      <div>ジャンル：<%= message.genre.name %></div>
      <div>体の部位：<%= message.body_parts.name %></div>
      <div>メッセージカテゴリー：<%= message.category.name %></div>
    </div>
  </div>
  <% end %>
</div>