config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
  }
  root 'messages#about'
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :messages do
    collection do
      get 'search' 
    end
    resources :helpful_messages, only: [:create, :destroy]
    resources :comments, only: [:index, :create, :edit, :update, :destroy]
  end
  
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-box1">
    <div class="footer-logo">baseball-info</div>
    <p>② 0202 baseball-info ine.</p>
  </div>
  <div class="footer-box2">
    <h1>サービス<h1><br>
    <ul>
      <li>メッセージ一覧</li>
      <li>有料会員サービス</li>
      <li>学生向けサービス</li>
      <li>ヘルプ</li>
    </ul>
  </div>
  <div class="footer-box3">
    <h1>サポート<h1><br>
    <ul>
      <li>運営会社</li>
      <li>採用情報</li>
      <li>利用規約</li>
      <li>団体向けサービス利用規約</li>
      <li>特定商取引法に基づく表示</li>
      <li>プライバシーポリシー</li>
    </ul>
  </div>
  <div class="footer-box4">
    <h1>団体向けサービス</h1><br>
    <%= link_to "baseball-info for team", "#", class: "footer-team-btn" %>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="header-left">
    <h1>baseball-info</h1>
    <%= link_to 'baseball-infoとは', root_path, class: "btn" %>
    <%= link_to 'メッセージ一覧', messages_path, class: "btn" %>
    <%= link_to 'ユーザー一覧', users_path, class: "btn" %>
  </div>
  <div class="header-right">
  <% if user_signed_in? %>
    <%= link_to current_user.nickname, user_path(current_user.id), class: "btn" %>
    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn" %>
    <%= link_to '新規作成', new_message_path, class: "btn" %>
  <% else %>
    <%= link_to 'ログイン', new_user_session_path, class: "btn" %>
    <%= link_to '会員登録', new_user_registration_path, class: "btn" %>
  <% end %>  
  </div>
</header>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>